apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-apisix-test
  namespace: argocd
spec:
  destination:
    namespace: test-apisix
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/simple-test-apisix
    repoURL: https://github.com/ArnaudCHT/test-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true